// Pure parsing of Claude Code session logs (~/.claude/projects/<project>/<sessionId>.jsonl).
// No VS Code imports here so it can be unit-tested with plain Node.

export type TitleSource = 'custom' | 'ai' | 'prompt' | 'command' | 'none';

export interface SessionInfo {
  id: string;
  filePath: string;
  /** Encoded folder name under the projects dir, e.g. "C--Users-me-repo". */
  projectDir: string;
  /** Working directory the session was started in. */
  cwd?: string;
  title: string;
  titleSource: TitleSource;
  firstPrompt?: string;
  lastPrompt?: string;
  gitBranch?: string;
  startTime?: number;
  lastTime?: number;
  /** Number of real prompts typed by the user (tool results and meta messages excluded). */
  promptCount: number;
  /** Number of distinct assistant API messages. */
  assistantCount: number;
  /** Messages received from other Claude sessions (agent teams). */
  peerMessageCount: number;
  firstPeerMessage?: { from: string; text: string };
  prUrl?: string;
  prNumber?: number;
  prRepository?: string;
  agentName?: string;
  version?: string;
  model?: string;
  /** Prompts, peer messages and Claude's replies (no tool I/O or thinking), for full-text search. */
  searchText: string;
}

export type TranscriptPart =
  | { kind: 'text'; text: string; from?: string }
  | { kind: 'thinking'; text: string }
  | {
      kind: 'tool_use';
      id?: string;
      name: string;
      /** Most telling input field (description, command, path…) for a one-line summary. */
      hint?: string;
      input: string;
      /** For edit-style tools: the replaced and replacement text. */
      diff?: { before: string; after: string };
      result?: { text: string; isError: boolean };
    }
  | { kind: 'tool_result'; text: string; isError: boolean };

export interface TranscriptEntry {
  role: 'user' | 'assistant' | 'tool' | 'system' | 'peer';
  timestamp?: string;
  parts: TranscriptPart[];
}

const MAX_TITLE = 120;
const MAX_TOOL_TEXT = 4000;

/** Lines that look like user messages but are generated by the CLI, not typed by the user. */
const NOISE_PATTERNS = [
  /^<local-command-(caveat|stdout|stderr)>/,
  /^<bash-(input|stdout|stderr)>/,
  /^<task-notification>/,
  /^<user-memory-input>/,
  /^\[Request interrupted by user/,
  /^Caveat: The messages below were generated by the user/,
];

type Classified =
  | { kind: 'prompt'; text: string }
  | { kind: 'command'; text: string }
  | { kind: 'noise' };

/** Classifies a user message's content as a real prompt, a slash command, or noise. */
export function classifyUserContent(content: unknown): Classified {
  let raw: string;
  if (typeof content === 'string') {
    raw = content;
  } else if (Array.isArray(content)) {
    if (content.some((p) => p && p.type === 'tool_result')) {
      return { kind: 'noise' };
    }
    raw = content
      .filter((p) => p && p.type === 'text' && typeof p.text === 'string')
      .map((p) => p.text as string)
      .join('\n');
  } else {
    return { kind: 'noise' };
  }

  const text = raw.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '').trim();
  if (!text) {
    return { kind: 'noise' };
  }

  if (text.startsWith('<command-name>') || text.startsWith('<command-message>')) {
    const name = /<command-name>([\s\S]*?)<\/command-name>/.exec(text)?.[1]?.trim() ?? '';
    const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(text)?.[1]?.trim() ?? '';
    const cmd = `${name} ${args}`.trim();
    return cmd ? { kind: 'command', text: cmd } : { kind: 'noise' };
  }

  if (NOISE_PATTERNS.some((re) => re.test(text))) {
    return { kind: 'noise' };
  }
  return { kind: 'prompt', text };
}

const PEER_MESSAGE = /<cross-session-message\b([^>]*)>([\s\S]*?)(?:<\/cross-session-message>|$)/;

/** Extracts a message sent by another Claude session (agent teams), which is logged as a meta user message. */
export function parsePeerMessage(content: unknown): { from: string; text: string } | undefined {
  const raw = typeof content === 'string' ? content : undefined;
  const m = raw ? PEER_MESSAGE.exec(raw) : null;
  if (!m) {
    return undefined;
  }
  const from = /from-name="([^"]*)"/.exec(m[1])?.[1] || 'another session';
  return { from, text: m[2].trim() };
}

export function oneLine(text: string, max = MAX_TITLE): string {
  const flat = text
    .replace(/<\/?pasted_content\b[^>]*>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return flat.length > max ? flat.slice(0, max - 1).trimEnd() + '…' : flat;
}

function parseTime(value: unknown): number | undefined {
  if (typeof value !== 'string') {
    return undefined;
  }
  const t = Date.parse(value);
  return Number.isNaN(t) ? undefined : t;
}

/** Parsed JSONL records, skipping blank and unparseable lines. */
export function* records(text: string): Generator<any> {
  let start = 0;
  while (start < text.length) {
    let end = text.indexOf('\n', start);
    if (end === -1) {
      end = text.length;
    }
    const line = text.slice(start, end).trim();
    start = end + 1;
    if (!line) {
      continue;
    }
    try {
      yield JSON.parse(line);
    } catch {
      // A partially written last line (session still running) or corrupt line; skip it.
    }
  }
}

/** Extracts summary metadata for one session log. */
export function parseSession(text: string, filePath: string, projectDir: string, id: string): SessionInfo {
  const info: SessionInfo = {
    id,
    filePath,
    projectDir,
    title: '',
    titleSource: 'none',
    promptCount: 0,
    assistantCount: 0,
    peerMessageCount: 0,
    searchText: '',
  };
  const searchParts: string[] = [];
  let customTitle: string | undefined;
  let aiTitle: string | undefined;
  let firstCommand: string | undefined;
  let lastPromptRecord: string | undefined;
  const assistantIds = new Set<string>();

  for (const r of records(text)) {
    if (!r || typeof r !== 'object') {
      continue;
    }
    switch (r.type) {
      case 'custom-title':
        if (typeof r.customTitle === 'string' && r.customTitle.trim()) {
          customTitle = r.customTitle.trim();
        }
        continue;
      case 'ai-title':
        if (typeof r.aiTitle === 'string' && r.aiTitle.trim()) {
          aiTitle = r.aiTitle.trim();
        }
        continue;
      case 'summary':
        // Older Claude Code versions stored the title as a "summary" record.
        if (typeof r.summary === 'string' && r.summary.trim() && !aiTitle) {
          aiTitle = r.summary.trim();
        }
        continue;
      case 'last-prompt':
        if (typeof r.lastPrompt === 'string') {
          lastPromptRecord = r.lastPrompt;
        }
        continue;
      case 'agent-name':
        if (typeof r.agentName === 'string') {
          info.agentName = r.agentName;
        }
        continue;
      case 'pr-link':
        if (typeof r.prUrl === 'string') {
          info.prUrl = r.prUrl;
          info.prNumber = typeof r.prNumber === 'number' ? r.prNumber : undefined;
          info.prRepository = typeof r.prRepository === 'string' ? r.prRepository : undefined;
        }
        continue;
      case 'user':
      case 'assistant':
        break;
      default:
        continue;
    }

    if (r.isSidechain) {
      continue;
    }
    if (!info.cwd && typeof r.cwd === 'string') {
      info.cwd = r.cwd;
    }
    if (typeof r.gitBranch === 'string' && r.gitBranch && r.gitBranch !== 'HEAD') {
      info.gitBranch = r.gitBranch;
    }
    if (typeof r.version === 'string') {
      info.version = r.version;
    }
    const t = parseTime(r.timestamp);
    if (t !== undefined) {
      info.startTime = info.startTime === undefined ? t : Math.min(info.startTime, t);
      info.lastTime = info.lastTime === undefined ? t : Math.max(info.lastTime, t);
    }

    if (r.type === 'assistant') {
      const msgId = r.message?.id ?? r.uuid;
      if (typeof msgId === 'string') {
        assistantIds.add(msgId);
      }
      const model = r.message?.model;
      if (typeof model === 'string' && !model.startsWith('<')) {
        info.model = model;
      }
      const content = r.message?.content;
      if (Array.isArray(content)) {
        for (const p of content) {
          if (p?.type === 'text' && typeof p.text === 'string' && p.text.trim()) {
            searchParts.push(p.text);
          }
        }
      }
      continue;
    }

    if (r.isMeta) {
      const peer = parsePeerMessage(r.message?.content);
      if (peer) {
        info.peerMessageCount++;
        info.firstPeerMessage ??= peer;
        searchParts.push(peer.text);
      }
      continue;
    }
    if (r.isCompactSummary) {
      continue;
    }
    const c = classifyUserContent(r.message?.content);
    if (c.kind === 'prompt') {
      info.promptCount++;
      info.firstPrompt ??= c.text;
      info.lastPrompt = c.text;
      searchParts.push(c.text);
    } else if (c.kind === 'command') {
      firstCommand ??= c.text;
    }
  }

  info.assistantCount = assistantIds.size;
  info.searchText = searchParts.join('\n');
  if (!info.lastPrompt && lastPromptRecord) {
    info.lastPrompt = lastPromptRecord;
  }

  if (customTitle) {
    info.title = oneLine(customTitle);
    info.titleSource = 'custom';
    // Agent-team sessions are all titled after the agent ("Project Lead"); add what the session was about.
    if (info.agentName && customTitle === info.agentName) {
      const about = aiTitle ?? info.firstPrompt ?? info.firstPeerMessage?.text;
      if (about) {
        info.title = oneLine(`${customTitle} — ${about}`);
      }
    }
  } else if (aiTitle) {
    info.title = oneLine(aiTitle);
    info.titleSource = 'ai';
  } else if (info.firstPrompt) {
    info.title = oneLine(info.firstPrompt);
    info.titleSource = 'prompt';
  } else if (info.firstPeerMessage) {
    info.title = oneLine(`${info.firstPeerMessage.from}: ${info.firstPeerMessage.text}`);
    info.titleSource = 'prompt';
  } else if (firstCommand) {
    info.title = oneLine(firstCommand);
    info.titleSource = 'command';
  } else {
    info.title = '(empty session)';
  }
  return info;
}

function stringifyToolContent(content: unknown): string {
  if (typeof content === 'string') {
    return content;
  }
  if (Array.isArray(content)) {
    return content
      .map((p) => {
        if (p?.type === 'text' && typeof p.text === 'string') {
          return p.text;
        }
        if (p?.type === 'image') {
          return '[image]';
        }
        return JSON.stringify(p);
      })
      .join('\n');
  }
  return content === undefined ? '' : JSON.stringify(content, null, 2);
}

function toolHint(input: unknown): string | undefined {
  if (!input || typeof input !== 'object') {
    return undefined;
  }
  const o = input as Record<string, unknown>;
  for (const key of ['description', 'command', 'file_path', 'path', 'pattern', 'url', 'query', 'prompt', 'skill']) {
    const v = o[key];
    if (typeof v === 'string' && v.trim()) {
      return oneLine(v, 140);
    }
  }
  return undefined;
}

function truncate(text: string, max = MAX_TOOL_TEXT): string {
  return text.length > max ? text.slice(0, max) + `\n… (${text.length - max} more characters)` : text;
}

/** Builds a readable transcript of the main conversation thread. */
export function parseTranscript(text: string): TranscriptEntry[] {
  const entries: TranscriptEntry[] = [];
  // tool_use parts by id, so results (logged later as user messages) can be attached to their call.
  const toolUses = new Map<string, Extract<TranscriptPart, { kind: 'tool_use' }>>();

  for (const r of records(text)) {
    if (!r || typeof r !== 'object' || r.isSidechain) {
      continue;
    }

    if (r.type === 'system' && r.subtype === 'compact_boundary') {
      entries.push({ role: 'system', timestamp: r.timestamp, parts: [{ kind: 'text', text: 'Conversation compacted' }] });
      continue;
    }

    if (r.type === 'assistant') {
      const content = r.message?.content;
      if (!Array.isArray(content)) {
        continue;
      }
      const parts: TranscriptPart[] = [];
      for (const p of content) {
        if (p?.type === 'text' && typeof p.text === 'string' && p.text.trim()) {
          parts.push({ kind: 'text', text: p.text });
        } else if (p?.type === 'thinking' && typeof p.thinking === 'string' && p.thinking.trim()) {
          parts.push({ kind: 'thinking', text: p.thinking });
        } else if (p?.type === 'tool_use') {
          const part: Extract<TranscriptPart, { kind: 'tool_use' }> = {
            kind: 'tool_use',
            id: typeof p.id === 'string' ? p.id : undefined,
            name: String(p.name ?? 'tool'),
            hint: toolHint(p.input),
            input: truncate(JSON.stringify(p.input ?? {}, null, 2)),
            diff:
              typeof p.input?.old_string === 'string' && typeof p.input?.new_string === 'string'
                ? { before: truncate(p.input.old_string), after: truncate(p.input.new_string) }
                : undefined,
          };
          if (part.id) {
            toolUses.set(part.id, part);
          }
          parts.push(part);
        }
      }
      if (!parts.length) {
        continue;
      }
      // Claude Code writes one line per content block and one message per tool round trip;
      // merge everything Claude does between two user prompts into a single turn.
      const prev = entries[entries.length - 1];
      if (prev?.role === 'assistant') {
        prev.parts.push(...parts);
      } else {
        entries.push({ role: 'assistant', timestamp: r.timestamp, parts });
      }
      continue;
    }

    if (r.type !== 'user') {
      continue;
    }
    if (r.isMeta) {
      const peer = parsePeerMessage(r.message?.content);
      if (peer) {
        entries.push({ role: 'peer', timestamp: r.timestamp, parts: [{ kind: 'text', text: peer.text, from: peer.from }] });
      }
      continue;
    }
    const content = r.message?.content;
    if (Array.isArray(content) && content.some((p) => p?.type === 'tool_result')) {
      const orphans: TranscriptPart[] = [];
      for (const p of content) {
        if (p?.type !== 'tool_result') {
          continue;
        }
        const result = { text: truncate(stringifyToolContent(p.content)), isError: !!p.is_error };
        const call = typeof p.tool_use_id === 'string' ? toolUses.get(p.tool_use_id) : undefined;
        if (call) {
          call.result = result;
        } else {
          orphans.push({ kind: 'tool_result', ...result });
        }
      }
      if (orphans.length) {
        entries.push({ role: 'tool', timestamp: r.timestamp, parts: orphans });
      }
      continue;
    }

    if (r.isCompactSummary) {
      continue;
    }
    const c = classifyUserContent(content);
    if (c.kind === 'noise') {
      continue;
    }
    entries.push({ role: 'user', timestamp: r.timestamp, parts: [{ kind: 'text', text: c.text }] });
  }
  return entries;
}

/** Best-effort decode of a project folder name ("C--Users-me-repo") back to a path, for sessions without a cwd. */
export function decodeProjectDir(name: string): string {
  const win = /^([A-Za-z])--(.*)$/.exec(name);
  if (win) {
    return `${win[1]}:\\${win[2].replace(/-/g, '\\')}`;
  }
  return name.replace(/-/g, '/');
}
